apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sre-multi-region-appset
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - matrix:
        generators:
          - list:
              elements:
                - region: local
                  cluster: minikube
                  label: staging
                # - region: uk-south
                #   cluster: sre-aks-uk-south
                #   label: production
                # - region: australia
                #   cluster: sre-aks-uk-north
                #   label: production
                

          - list:
              elements:
                - app: boutique
                  project: boutique
                  path: base
                  namespace: default
                  helm: "false"
                  serverSideApply: "false"

                - app: kyverno-policies
                  project: kyverno
                  path: platform/policies/
                  namespace: default
                  helm: "false"
                  serverSideApply: "true"

  template:
    metadata:
      name: '{{.app}}-{{.region}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: '{{.project}}'

      source:
        repoURL: https://github.com/kennethchinedu/HE-multi-cloud-hybrid-kubernetes-project
        targetRevision: main
        path: '{{.path}}'
        # {{- if eq .helm "true" }}
        # helm:
        #   valueFiles:
        #     - values.yaml
        # {{- end }}

      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          # {{- if eq .serverSideApply "true" }}
          # - ServerSideApply=true
          # {{- end }}
        retry:
          limit: 3
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 2m