# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {

    helm = {
      source  = "hashicorp/helm"
      version = ">= 3.0.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }

  }
}



provider "helm" {
  kubernetes = {
    config_path = "~/.kube/config"

  }
}
